### ISSUE TITLE
Is the scraper working for you?

### ISSUE THREAD

**Issue by wireman21** [DIGITALCRIMINALS/UltimaScraper#1052]
On UltimaScraper-7.9.0.

I get an endless loop that looks like this:

Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
0
Choose Profiles: 0 = All |
0
Choose Subscriptions: 0 = All |
0
[2023-07-28 02:54:27] Assigning Jobs
[2023-07-28 02:54:27] Archive Completed in 0.03 Minutes
Choose Profiles: 0 = All |
0
Choose Subscriptions: 0 = All |

**Comment by penguinpatrol** [comment]
getting that too any fixes?

**Comment by TheSulak3** [comment]
Same thing over here, no fixes at all as far as I can see

**Comment by dvfaa** [comment]
Make sure "active": true in your auth.json file for the profile you're loading, sometimes after an update it gets changed to null for some reason. If that doesn't work I would recommend deleting the auth.json and running the program and filling out all of the info again(make sure "active": true as well). This is how I've fixed it whenever I had that issue

**Comment by 279993** [comment]
Sorry to bump ,but still having the issue. clearing the cache does not fix it.
